language: generic

dist: bionic

jobs:
    include:
    - env: CXX=g++-10 CC=gcc-10
      addons:
        apt:
          packages:
            - g++-10
            - valgrind
          sources: &sources
            - ubuntu-toolchain-r-test
            - llvm-toolchain-bionic-9
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    - env: CXX=g++-9 CC=gcc-9
      addons:
        apt:
          packages:
            - g++-9
            - valgrind
          sources: *sources
    - env: CXX=g++-8 CC=gcc-8
      addons:
        apt:
          packages:
            - g++-8
            - valgrind
          sources: *sources
    - env: CXX=g++-7 CC=gcc-7
      addons:
        apt:
          packages:
            - g++-7
            - valgrind
          sources: *sources
    - env: CXX=g++-6 CC=gcc-6 EXTRA_CMAKE=-DDEFLATE_SUPPORT=Off
      addons:
        apt:
          packages:
            - g++-6
            - valgrind
          sources: *sources
    - env: CXX=g++-6 CC=gcc-6
      addons:
        apt:
          packages:
            - g++-6
            - valgrind
          sources: *sources
    - env: CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - g++-5
            - valgrind
          sources: *sources
    - env: CXX=clang++-10 CC=clang-10
      addons:
        apt:
          packages:
            - clang-10
            - libc++-10-dev
            - libc++abi-10-dev
            - valgrind
          sources: *sources
    - env: CXX=clang++-9 CC=clang-9
      addons:
        apt:
          packages:
            - clang-9
            - libc++-9-dev
            - libc++abi-9-dev
            - valgrind
          sources: *sources
    - env: CXX=clang++-8 CC=clang-8
      addons:
        apt:
          packages:
            - clang-8
            - libc++-8-dev
            - libc++abi-8-dev
            - valgrind
          sources: *sources
    - env: CXX=clang++-7 CC=clang-7
      addons:
        apt:
          packages:
            - clang-7
            - libc++-7-dev
            - libc++abi-7-dev
            - valgrind
          sources: *sources

install:
    - if [[ "$CXX" == clang* ]]; then export CXXFLAGS="-stdlib=libc++"; fi
    - JOBS=2

before_script:
    - cmake --version
    - cmake . -Bbuild -DCMAKE_BUILD_TYPE=Release -DCOVERAGE=On ${EXTRA_CMAKE}
    - cmake --build build -- -j${JOBS}

script:
    - cd build
    - cmake --build . --target test
    - ctest -D ExperimentalBuild -j${JOBS}
    - ctest -D ExperimentalMemCheck -j${JOBS}
    - bash <(curl -s https://codecov.io/bash)
